source = $HOME/.config/hypr/mocha.conf

$accent = $mauve
$accentAlpha = $mauveAlpha
$font = Caskaydia Cove Nerd Font

# GENERAL
general {
    disable_loading_bar = true
    hide_cursor = true
}

# BACKGROUND
background {
    monitor =
    #path = ~/.config/backgrounds/nice-blue-background.png
    #path = ~/.config/backgrounds/shaded_landscape.jpg
    #path = ~/.config/backgrounds/island-night-moon-scenery-digital-art-4k-wallpaper-uhdpaper.com-289@0@j.jpg
    #path = ~/.config/backgrounds/crane.png
    #path = ~/.config/backgrounds/signal-enthusiast.jpg
    path = screenshot
    blur_passes = 2
    color = $base
}

# HOURS 
label {
    monitor =
    text = cmd[update:1000] echo "<b>$(date +"%H")</b>"
    color = $text
    font_size = 130
    font_family = $font
    position = -85, 225       # Το πήγαμε 5 pixels πιο αριστερά και 5 πιο πάνω
    halign = center
    valign = center
}

# MINUTES 
label {
    monitor =
    text = cmd[update:1000] echo "<b>$(date +"%M")</b>"
    color = $text
    font_size = 130
    font_family = $font
    position = 85, 95         # Το πήγαμε 5 pixels πιο δεξιά και 15 πιο κάτω
    halign = center
    valign = center
}

# DATE 
label {
    monitor = 
    text = cmd[update:43200000] echo "$(date +"%A, %d %B %Y")"
    color = $subtext0
    font_size = 22
    font_family = $font
    position = 0, -10       # Το φέραμε λίγο πιο πάνω για να δέσει με τα λεπτά
    halign = center
    valign = center
}

# INPUT FIELD (Ακόμα πιο κάτω)
input-field {
    monitor =
    size = 300, 60
    outline_thickness = 0
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = $accent
    inner_color = rgba(30, 30, 46, 0.5)
    font_color = $text
    fade_on_empty = false
    placeholder_text = <span foreground="##$textAlpha"><i>󰌾 Logged in as </i><span foreground="##$accentAlpha">$USER</span></span>
    hide_input = false
    check_color = $accent
    fail_color = $red
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = $yellow
    position = 0, -130      # Το σπρώχνουμε 130 pixels ΚΑΤΩ από το κέντρο
    halign = center
    valign = center
}
